import os
import google.generativeai as genai
from typing import List, Optional

# --- Configuration ---
# API Key should be set in the environment variable 'GEMINI_API_KEY'
API_KEY_VAR = 'GEMINI_API_KEY'

def configure_api() -> bool:
    """
    Configures the Google Generative AI API with the key from environment variables.
    Returns True if successful, False if key is missing.
    """
    api_key = os.getenv(API_KEY_VAR)
    if not api_key:
        print(f"Error: API Key not found in environment variable '{API_KEY_VAR}'.")
        return False
    
    genai.configure(api_key=api_key)
    return True

def generate_explanation(poem_text: str, 
                         primary_emotion: str, 
                         secondary_emotions: List[str], 
                         model_name: str = 'gemini-2.5-flash') -> str:
    """
    Generates a qualitative explanation for why the given emotions fit the poem
    using a Large Language Model (LLM).

    This function does NOT predict emotions. It explains the *provided* labels.

    Args:
        poem_text (str): The original text of the poem.
        primary_emotion (str): The predicted primary emotion label.
        secondary_emotions (List[str]): A list of predicted secondary emotion labels.
        model_name (str): The Gemini model version to use.

    Returns:
        str: A text explanation generated by the LLM.
    """
    
    # 1. Check Configuration
    if not configure_api():
        return "[Error: API functionality unavailable due to missing API Key.]"

    # 2. Construct Prompt
    # We explicitly instruct the model to EXPLAIN, not PREDICT.
    secondary_str = ", ".join(secondary_emotions) if secondary_emotions else "None"
    
    prompt = f"""
You are an expert in literay analysis, specifically focusing on Indian aesthetics (Navarasa) and poetic emotion.

Your task is to provide a QUALITATIVE EXPLANATION for the emotions identified in the following poem.
DO NOT predict new emotions. Use the provided labels as the ground truth for your analysis.

--------------------------------------------------
POEM:
{poem_text}

IDENTIFIED EMOTIONS:
- Primary Emotion: {primary_emotion}
- Secondary Emotion(s): {secondary_str}
--------------------------------------------------

INSTRUCTIONS:
1. Explain WHY these emotions are appropriate for this poem.
2. Identify specific contextual cues in the text, such as:
   - Words indicating devotion (Bhakti), morality, or philosophy.
   - Nature imagery or symbolism (e.g., flowers, rivers, darkness).
   - Tone and mood.
3. Map the identified emotions to the corresponding Indian aesthetic concept (Rasa) if applicable (e.g., Karuna for Sadness, Shringara for Love/Devotion, Shanta for Peace).
4. Keep the explanation concise (approx. 100-150 words).

OUTPUT FORMAT:
Start your response with: "**LLM-generated qualitative explanation:**"
Then provide the analysis in plain text.
    """

    # 3. Call API with Retry Logic
    import time
    from google.api_core import exceptions
    
    max_retries = 3
    retry_delay = 5  # Start with 5 seconds

    for attempt in range(max_retries):
        try:
            model = genai.GenerativeModel(model_name)
            response = model.generate_content(prompt)
            
            # 4. Return Result
            if response.text:
                return response.text
            else:
                return "[Error: Empty response from LLM.]"

        except exceptions.ResourceExhausted:
            if attempt < max_retries - 1:
                print(f"Rate limited (429). Retrying in {retry_delay} seconds...")
                time.sleep(retry_delay)
                retry_delay *= 2  # Exponential backoff
            else:
                return "[Error: Rate limit exceeded. Please try again later.]"
        
        except Exception as e:
            # Basic error handling
            return f"[Error: Failed to generate explanation. Details: {str(e)}]"

# --- Example Usage (for testing) ---
if __name__ == "__main__":
    # Mock data for demonstration
    sample_poem = "Prabhu mere avagun chit na dharo. Samadarshi hai naam tiharo."
    sample_primary = "Devotion"
    sample_secondary = ["Humility", "Surrender"]
    
    print("--- Testing Explanation Module ---\n")
    
    # Check if key is present just for this run
    if os.getenv(API_KEY_VAR):
        explanation = generate_explanation(sample_poem, sample_primary, sample_secondary)
        print(explanation)
    else:
        print(f"Skipping actual API call. Set {API_KEY_VAR} to test.")
        print(f"Function `generate_explanation` is ready to use.")
